### PR TITLE
upgrade fxamacker/cbor from v1.5.1 to v2.3.0

### PR DESCRIPTION
**Pull request by x448**
## Please describe the change you are making

Upgrade fxamacker/cbor from v1.5.1 to v2.3.0.

v2.3.0 fixes all known bugs and surpassed 1+ billion execs in fuzz tests.

For more info, see [release notes](https://github.com/fxamacker/cbor/releases/tag/v2.3.0).

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes, I'm the owner of all the coding changes to auditlog in this PR and am contributing those changes to auditlog.

## The code will be published under the MIT-0 license. Have you read and understood this license?

Yes.

### CODE REVIEW

**Comment by janoszen** [comment]
Hello @x448, thank you very much for your contribution. Please allow us a few days to review the changes in the CBOR library and make sure that the audit logs are backwards-compatible.

**Comment by x448** [comment]
> Hello @x448, thank you very much for your contribution. Please allow us a few days to review the changes in the CBOR library and make sure that the audit logs are backwards-compatible.

Hello @janoszen, for backwards compatibility, you may want to look at adjusting the options for max number of array elements and map pairs. That's the only compatibility pitfall that comes to mind.

```Go
const MaxArrayElements = 1024 * 256 // this limit can be set as high as 2147483647
const MaxMapPairs = 1024 * 256      // this limit can be set as high as 2147483647
```

For improved security, you may want to see [safer-cbor](https://github.com/x448/safer-cbor).  Its  [cbor.go.txt](https://raw.githubusercontent.com/x448/safer-cbor/master/cbor.go.txt) shows an example use of fxamacker/cbor that enables Core Deterministic Encoding (RFC 8949), duplicate map key detection, and forbids indefinite length items.  It avoids using helper functions like cbor.CoreDetEncOptions() so each available setting can be reviewed.

**Comment by janoszen** [comment]
Awesome, thank you!

**Review by janoszen — APPROVED** [review]

**Comment by ghost** [comment]
@x448 thank you very much, sorry this took so long. Feel free to add yourself to the contributors list on the website by editing this file: https://github.com/ContainerSSH/containerssh.github.io/blob/main/contributors.yaml

**Pull request merged**
